otrs:
  #image: juanluisbaptiste/otrs:latest
  build: otrs
  ports:
  - "80:80"
# If running behind a proxy container, expose the ports instead
# and link the proxy container to this one.
#  expose:
#  - "80"
  links:
  - mariadb:mariadb
  - postfix:postfix
# env_file: ../docker-otrs/otrs-setup.env
  volumes_from:
  - data-otrs
# If you want to run the installer, uncomment this:
  environment:
       OTRS_INSTALL: "no"
       OTRS_DB_PASSWORD: "changeme"
       OTRS_ROOT_PASSWORD: "changeme"
       MYSQL_ROOT_PASSWORD: "changeme"
#    OTRS_INSTALL: "restore"
#   OTRS_BACKUP_DATE: "2016-11-08_15-58"
mariadb:
  #image: juanluisbaptiste/otrs-mariadb:latest
  build: mariadb
  expose:
  - "3306"
  volumes_from:
    - data
  environment:
      MYSQL_ROOT_PASSWORD: "changeme"
postfix:
   image: postfix
   expose:
   - "25"
   env_file: ../smtp-credentials.env
data:
  image: centos/mariadb:latest
  volumes:
  - ./volumes/mysql:/var/lib/mysql
  - "/etc/localtime:/etc/localtime:ro"
  command: /bin/true
data-otrs:
  image: juanluisbaptiste/otrs:latest
  volumes:
  - ./volumes/config:/opt/otrs/Kernel
  - "./otrs/backup:/var/otrs/backups"
  - "/etc/localtime:/etc/localtime:ro"
  command: /bin/true
